version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # The location of requirements.txt
    schedule:
      interval: "weekly"
    versioning-strategy: "increase" # Allow updates only when the version increases
    ignore:
      - dependency-name: "Flask"
        versions: ["2.0.x"]
