name: "DB Connection Test"

on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ]  

jobs:
  db-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymysql cryptography

      - name: Test Cloud MySQL Connection
        env:
          USER: ${{ secrets.USER }}
          PWD: ${{ secrets.PWD }}
        run: |
          python -c "
          import mysql_connector as sql
          print('${{ secrets.USER }}', f'secrets.USER') # testing...
          try:
              sql.connect('${{ secrets.USER }}', '${{ secrets.PWD }}')
              print('✅ Connected to Cloud MySQL!')
          except Exception as e:
              print(f'❌ Connection failed: {e}')
              exit(1)
          finally:
              if sql.db_connector:
                  sql.close()
          "
